// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using ReactSupply.Models.DB;
using System;

namespace ReactSupply.Migrations
{
    [DbContext(typeof(SupplyChainContext))]
    [Migration("20180505041909_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ReactSupply.Models.DB.ConfigurationMain", b =>
                {
                    b.Property<int>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ModuleID")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("ValueName")
                        .HasMaxLength(50);

                    b.Property<string>("ControlType")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("('text')")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Css")
                        .IsUnicode(false);

                    b.Property<string>("DefaultText")
                        .HasMaxLength(1000);

                    b.Property<string>("Description")
                        .HasMaxLength(1000);

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100);

                    b.Property<string>("Editor")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("FilterRenderer")
                        .HasColumnName("filterRenderer")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Formatter")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Group")
                        .HasMaxLength(100);

                    b.Property<string>("HeaderRenderer")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsEditable");

                    b.Property<bool>("IsFilterable");

                    b.Property<bool>("IsLocked");

                    b.Property<bool>("IsRequired");

                    b.Property<bool>("IsResizeable");

                    b.Property<bool>("IsSortable");

                    b.Property<bool>("IsVisible");

                    b.Property<int?>("MaxLength")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("((2000))");

                    b.Property<int?>("MinLength")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("((0))");

                    b.Property<decimal?>("Position")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<int?>("Width")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("((6))");

                    b.HasKey("ModuleId", "ValueName");

                    b.ToTable("ConfigurationMain");
                });

            modelBuilder.Entity("ReactSupply.Models.DB.SupplyRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ModuleID")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("ValueName")
                        .HasMaxLength(50);

                    b.Property<string>("Identifier")
                        .IsRequired();

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("(suser_name())")
                        .HasMaxLength(30);

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Data")
                        .HasMaxLength(1000);

                    b.Property<string>("ModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("(suser_name())")
                        .HasMaxLength(30);

                    b.Property<DateTime?>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id", "ModuleId", "ValueName");

                    b.ToTable("SupplyRecord");
                });
#pragma warning restore 612, 618
        }
    }
}
