INSERT INTO ConfigurationMain(ModuleID,ValueName,DisplayName,ControlType,Position) VALUES(0,'No', 'No.', 'input', '0')
INSERT INTO ConfigurationMain(ModuleID,ValueName,DisplayName,ControlType,Position) VALUES(0,'SoReceivedDate', 'SO Received DATE', 'date', '1')
INSERT INTO ConfigurationMain(ModuleID,ValueName,DisplayName,ControlType,Position) VALUES(0,'SoIssuedDate', 'SO Issued DATE', 'date', '2')
INSERT INTO ConfigurationMain(ModuleID,ValueName,DisplayName,ControlType,Position) VALUES(0,'ProductType', 'Product Type', 'input', '3')
INSERT INTO ConfigurationMain(ModuleID,ValueName,DisplayName,ControlType,Position) VALUES(0,'Brand', 'BRAND', 'input', '4')
INSERT INTO ConfigurationMain(ModuleID,ValueName,DisplayName,ControlType,Position) VALUES(0,'PO', 'P/O', 'input', '5')
INSERT INTO ConfigurationMain(ModuleID,ValueName,DisplayName,ControlType,Position) VALUES(0,'AX6SO', 'AX6 SO#', 'input', '6')
INSERT INTO ConfigurationMain(ModuleID,ValueName,DisplayName,ControlType,Position) VALUES(0,'Remark1', 'Remark', 'area', '7')
INSERT INTO ConfigurationMain(ModuleID,ValueName,DisplayName,ControlType,Position) VALUES(0,'RETD', 'RETD', 'date', '8')
INSERT INTO ConfigurationMain(ModuleID,ValueName,DisplayName,ControlType,Position) VALUES(0,'OriginalCETD', 'ORIGINAL CETD', 'date', '9')
INSERT INTO ConfigurationMain(ModuleID,ValueName,DisplayName,ControlType,Position) VALUES(0,'CETDLater; Maintain/Revised (Follow BB CETD/ Requested By Sales/ Others)', 'CETD Later; Maintain/Revised (Follow BB CETD/ Requested By Sales/ Others)', 'date', '10')
INSERT INTO ConfigurationMain(ModuleID,ValueName,DisplayName,ControlType,Position) VALUES(0,'ShipmentBookingETD', 'Shipment Booking ETD', 'date', '11')
INSERT INTO ConfigurationMain(ModuleID,ValueName,DisplayName,ControlType,Position) VALUES(0,'ShipmentBookingETA', 'Shipment Booking ETA', 'date', '12')
INSERT INTO ConfigurationMain(ModuleID,ValueName,DisplayName,ControlType,Position) VALUES(0,'ActualPortClosingdate', 'Actual Port Closing date', 'date', '13')
INSERT INTO ConfigurationMain(ModuleID,ValueName,DisplayName,ControlType,Position) VALUES(0,'RemarkForShipmentissue', 'Remark for shipment issue', 'area', '14')
INSERT INTO ConfigurationMain(ModuleID,ValueName,DisplayName,ControlType,Position) VALUES(0,'PMdeliverydate1', 'PM delivery date', 'date', '15')
INSERT INTO ConfigurationMain(ModuleID,ValueName,DisplayName,ControlType,Position) VALUES(0,'PMdeliverydate2', 'PM delivery date', 'date', '16')
INSERT INTO ConfigurationMain(ModuleID,ValueName,DisplayName,ControlType,Position) VALUES(0,'PMdeliverydate3', 'PM delivery date', 'date', '17')
INSERT INTO ConfigurationMain(ModuleID,ValueName,DisplayName,ControlType,Position) VALUES(0,'Completiondate1', 'Completion date', 'date', '18')
INSERT INTO ConfigurationMain(ModuleID,ValueName,DisplayName,ControlType,Position) VALUES(0,'Completiondate2', 'Completion date', 'date', '19')
INSERT INTO ConfigurationMain(ModuleID,ValueName,DisplayName,ControlType,Position) VALUES(0,'InternalInspection1', 'Internal Inspection', 'input', '20')
INSERT INTO ConfigurationMain(ModuleID,ValueName,DisplayName,ControlType,Position) VALUES(0,'InternalInspection2', 'Internal Inspection', 'input', '21')
INSERT INTO ConfigurationMain(ModuleID,ValueName,DisplayName,ControlType,Position) VALUES(0,'ReworkCompletiondate', 'Rework Completion date', 'date', '22')
INSERT INTO ConfigurationMain(ModuleID,ValueName,DisplayName,ControlType,Position) VALUES(0,'ReworkCompletiondateResult', 'Rework Completion date Result (pass/ fail)', 'input', '23')
INSERT INTO ConfigurationMain(ModuleID,ValueName,DisplayName,ControlType,Position) VALUES(0,'RemarkExternalInspection', 'Remark External Inspection', 'input', '24')
INSERT INTO ConfigurationMain(ModuleID,ValueName,DisplayName,ControlType,Position) VALUES(0,'ExternalInspection', 'External Inspection', 'input', '25')
INSERT INTO ConfigurationMain(ModuleID,ValueName,DisplayName,ControlType,Position) VALUES(0,'ReworkCompletiondate', 'Rework Completion date', 'input', '26')
INSERT INTO ConfigurationMain(ModuleID,ValueName,DisplayName,ControlType,Position) VALUES(0,'ReworkCompletiondateResult', 'Rework Completion date Result (pass/ fail)', 'input', '27')
INSERT INTO ConfigurationMain(ModuleID,ValueName,DisplayName,ControlType,Position) VALUES(0,'Remark2', 'Remark', 'area', '28')
INSERT INTO ConfigurationMain(ModuleID,ValueName,DisplayName,ControlType,Position) VALUES(0,'LoadingDate1', 'Loading Date', 'date', '29')
INSERT INTO ConfigurationMain(ModuleID,ValueName,DisplayName,ControlType,Position) VALUES(0,'LoadingDate2', 'Loading Date', 'date', '30')
INSERT INTO ConfigurationMain(ModuleID,ValueName,DisplayName,ControlType,Position) VALUES(0,'ContainerTruckOutStatus', 'Container Truck Out Status', 'input', '31')
INSERT INTO ConfigurationMain(ModuleID,ValueName,DisplayName,ControlType,Position) VALUES(0,'Remark3', 'Remark', 'area', '32')

